---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
  become_user: "{{ openclaw_user }}"
  become: true
  environment: "{{ openclaw_user_manager_environment }}"
- name: Restart OpenClaw
  ansible.builtin.systemd_service:
    name: openclaw-gateway.service
    state: restarted
    scope: user
  become_user: "{{ openclaw_user }}"
  become: true
  environment: "{{ openclaw_user_manager_environment }}"
